hostname: ubuntu
manage_etc_hosts: true

users:
  - name: turk
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHMlkVBdWPXL5Ry+VjUsvFTiLYdRvAuSUjVUlle8wkR turk@goose

disable_root: true

packages:
  - vim
  - tree
  - curl
  - git
  - python3
  - iproute2
  - iw
  - iputils-ping
  - wireguard
  - tcpdump
  - nmap
  - traceroute
  - btop

runcmd:
  - apt-get update
  - apt-get upgrade -y
  - git clone https://github.com/turkosaurus/dotfiles
  - find dotfiles/bin/ -type f -exec chmod +x {} \;
  - dotfiles/bin/sync
  - dotfiles/install/neovim
  - echo "Cloud-init complete! $(date)!" >> /etc/motd
